name: Gradle build

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: liberica
      - name: execute build
        uses: gradle/gradle-build-action@v3.4.2
        with:
          arguments: build
